#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Castro documentation build configuration file, created by
# sphinx-quickstart on Mon Dec 25 18:42:54 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import re
import sys
import shlex
import subprocess

sys.path.insert(0, os.path.abspath('../../'))



# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.mathjax',
              'sphinx_math_dollar',
              'sphinx.ext.ifconfig',
              'sphinx.ext.viewcode',
              'sphinxcontrib.bibtex',
              'sphinx.ext.autosummary',
              'sphinx_math_dollar',
              'sphinx_design',
              'sphinx.ext.githubpages',
              'sphinx_copybutton',
              'sphinx-prompt',
              'IPython.sphinxext.ipython_console_highlighting']

# bibtex
bibtex_bibfiles = []

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# see https://github.com/phn/pytpm/issues/3#issuecomment-12133978
numpydoc_show_class_members = False

# The main toctree document.
main_doc = 'index'

# General information about the project.
project = 'PHY 504'
copyright = '2022-2024, Michael Zingale'
author = 'Michael Zingale'

#html_logo = "castro_logo_hot_200.png"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = "Spring 2024"
# The full version, including alpha/beta/rc tags.
release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['**.ipynb_checkpoints']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'default'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for MathJax
# -- Options for MathJax
# for sphinx-math-dollar
mathjax3_config = {}

mathjax3_config["tex"] = {
    "inlineMath": [['\\(', '\\)']],
    "displayMath": [["\\[", "\\]"]],
  }

mathjax3_config["tex"]["macros"] = {}

with open('mathsymbols.tex', 'r') as f:
    for line in f:
        macros = re.findall(r'\\newcommand{\\(.*?)}(\[(\d)\])?{(.+)}', line)
        for macro in macros:
            if len(macro[1]) == 0:
                mathjax3_config['tex']['macros'][macro[0]
                                                ] = "{" + macro[3] + "}"
            else:
                mathjax3_config['tex']['macros'][macro[0]] = [
                    "{" + macro[3] + "}", int(macro[2])]


numfig = True

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_book_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    "repository_url": "https://github.com/zingale/phy504",
    "use_repository_button": True,
    "use_issues_button": True,
    "use_source_button": True,
    "repository_branch": "main",
    "path_to_docs": "docs/source",
    "logo": {
        "text": "PHY 504",
    },
    "use_download_button": False
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_css_files = []


